### ISSUE TITLE
fizzysearch FEATURE REQUEST date functions

### ISSUE THREAD

**Issue by ch-sander** [epoz/shmarql#28]
A magic predicate to calculate date difference as in SQL would be wonderful

**Comment by epoz** [comment]
I am busy moving all actual implementations of the search code out of the shmarql repo and into the fizzysearch repo: https://github.com/ISE-FIZKarlsruhe/fizzysearch 
This makes it more clear/modular, and will allow the fizzysearch code to be used in other contexts.

**Comment by epoz** [comment]
Also, at the moment fizzysearch works as a query rewriter, so it is done _before_ the query is processed by the back-end triplestore. So #26 #27 and #28 would not work in fizzysearch, as they would require actual processing inside the sparql processor.

**Comment by ch-sander** [comment]
> I am busy moving all actual implementations of the search code out of the shmarql repo and into the fizzysearch repo: https://github.com/ISE-FIZKarlsruhe/fizzysearch 
> This makes it more clear/modular, and will allow the fizzysearch code to be used in other contexts.

Makes sense.

**Comment by ch-sander** [comment]
> Also, at the moment fizzysearch works as a query rewriter, so it is done _before_ the query is processed by the back-end triplestore. So #26 #27 and #28 would not work in fizzysearch, as they would require actual processing inside the sparql processor.

Understood. Yet, it would be a great expansion of a query tool. If you have any ideas about how this could be done, I can maybe request help from someone else for an implementation if out of scope for fizzysearch

**Comment by ch-sander** [comment]
Datediff is shipped with oxigraph already 
https://github.com/oxigraph/oxigraph/wiki/SPARQL

`xsd:duration` results may need further parsing

`Log` is easy to implement as `custom_functions` argument in the `query` function of pyoxigraph 
https://github.com/oxigraph/oxigraph/blob/9502c66d7e960ab2a0936d65288857c13ae76a20/python/tests/test_store.py#L198

Custom functions for aggregations will be supported in the future by oxigraph, so also median and similar statistics will be rather trivial.

Thanks @tpt for the insights!

**Comment by epoz** [comment]
I am **super** excited to learn that it is possible to do custom functions, wish I had known about it earlier. It was there in the tests all along, but not mentioned in the docs.

@Tpt this is huge. (if I understand it correctly) My head is spinning with the potential applications. Can't wait to test it more.

Thanks @ch-sander for pointing this out!

**Comment by epoz** [comment]
Alas, my enthusiasm was a bit too much. The custom functions seem to only be able to return a single value.
@Tpt is there any way to also return an iterator from a custom function so that for example a variable could be filled with values sourced externally from the triplestore?
(similar to how virtual knoweldge graphs work)

**Comment by ch-sander** [comment]
I dare to answer for @Tpt as we've been discussing this already: aggregation in custom functions is coming soon.

**Comment by Tpt** [comment]
>  @Tpt is there any way to also return an iterator from a custom function so that for example a variable could be filled with values sourced externally from the triplestore?

Sadly, there is no easy way right now. We would have to implement something like [this](https://awslabs.github.io/SPARQL-CDTs/spec/latest.html) in Oxigraph.

However, what is currently possible right now using Oxigraph Rust API is to implement [custom `SERVICE`s](https://docs.rs/oxigraph/latest/oxigraph/sparql/trait.ServiceHandler.html). This way it is possible to build virtual knowledge graphs. However the API is quite cumbersome to use because services take for input a SPARQL query. Exposing it to Python means that either the query would be presented as a string that needs to be parsed again or as an AST for which we need to design an API.
